version: '3.1'
services:
  micro-streaming:
    image: micro-streaming
    environment:
      - spring.data.mongodb.uri=mongodb://root:example@mongo:27017/
      - spring.data.mongodb.database=test
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.username=root
      - spring.rabbitmq.password=example
      - rabbitmq.batch.size=10
      - rabbitmq.consume.rate=40000
      - rabbitmq.produce.rate=30000
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=example